### ISSUE TITLE
When using the Search function in Numbers tab, system returns a 404

### ISSUE THREAD

**Issue by scottbarstow** [RestComm/design#76] opened 2017-01-31 14:28 UTC
This is in Search existing numbers, not searching for Provider numbers

Get the following error:

JBWEB000065: HTTP Status 404 - /search

JBWEB000309: type JBWEB000067: Status report

JBWEB000068: message /search

JBWEB000069: description JBWEB000124: The requested resource is not available.

JBoss Web/7.2.0.Final

**Comment by deruelle** [comment] 2017-02-07 08:56
@scottbarstow I can't reproduce on cloud. Can you provide the steps to reproduce and potentially some screenshots ?

**Comment by scottbarstow** [comment] 2017-02-07 14:07
Type a value into search. It filters down. If you then hit enter, you get the error. See attached @deruelle 


![screen shot 2017-02-07 at 9 05 50 am](https://cloud.githubusercontent.com/assets/746403/22694315/bfa3e432-ed14-11e6-94f3-a012fe4ddcc6.png)

![screen shot 2017-02-07 at 9 06 01 am](https://cloud.githubusercontent.com/assets/746403/22694317/c32018ba-ed14-11e6-930a-dd993c6e0a0a.png)

**Comment by deruelle** [comment] 2017-02-08 08:51
Thanks @scottbarstow. Confirmed. Assigning to @brainslog and tied to https://github.com/RestComm/Restcomm-Connect/issues/1455

**Comment by ipsilantide** [comment] 2017-02-21 11:21
Issue moved to [RestComm/Restcomm-Connect #1867](https://github.com/RestComm/Restcomm-Connect/issues/1867) via [**ZenHub**](https://www.zenhub.com/)

**Closed as completed by ipsilantide** 2017-02-21 11:21 UTC
